### ISSUE TITLE
How to start local development?

### ISSUE THREAD

**Issue by mackdunkan** [elm-fullstack/elm-fullstack#18]
Hi!
![image](https://user-images.githubusercontent.com/16391860/169010422-bb7d6afe-6f89-49b2-8215-c3a94f8390f2.png)

**Comment by Viir** [comment]
If you want to start development with a complete working app as a template, an easy way is to download the contents of this repository and use the example app from `implement\example-apps\minimal-backend-hello-world`
You can run a server with this command:

```
elm-fs  run-server  --public-urls="http://*:5000"  --deploy="C:\Users\John\Downloads\elm-fullstack-main\implement\example-apps\minimal-backend-hello-world"
```

(You can use the `Download ZIP` button in the GitHub UI to download the repository or use `git  clone`)

![image](https://user-images.githubusercontent.com/19209696/169495854-d2f5b18d-1e47-4503-8dc8-3e0b5a7e085c.png)

**Comment by mackdunkan** [comment]
Thanks for the answer!
Can I use this for an online store or blog?
I have somewhere around 50 thousand products and about 5 thousand users

**Comment by Viir** [comment]
Yes, it works for online stores and blogs. Fifty thousand items are within the supported limits.

But another metric to consider is the size of your database. At the moment (with the current implementation), the size of the database is limited to a few hundred MB.

**Comment by mackdunkan** [comment]
Thanks for the answer
and what aisles the number of elements no longer supports?
What will happen if the database exceeds the limit?
how to deal with SEO for robots, are there any examples?

**Comment by Viir** [comment]
I will run a test to measure the exact limits of today's implementation.
Regarding SEO for robots (crawlers), I recommend https://moz.com/beginners-guide-to-seo/how-search-engines-operate
That article also has many examples and also

**Comment by Viir** [comment]
I ran a test and found another important limit for total app state size: App state sizes of more than 166.6 MB will usually crash the server with v2022-03-20.

Therefore elm-fs is not currently fit for that workload.

Restarting a server with v2022-03-20 crashed with this exception:

```
Application startup exception: System.ArgumentException: The JSON value of length 168831530 is too large and not supported.
   at System.Text.Json.ThrowHelper.ThrowArgumentException_ValueTooLarge(Int32 tokenLength)
   at System.Text.Json.Serialization.Converters.StringConverter.Write(Utf8JsonWriter writer, String value, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteStringUsingSerializer[TValue](TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at ElmFullstack.WebHost.PersistentProcess.PersistentProcessLiveRepresentation.AttemptProcessEvent(IProcessWithStringInterface process, AppEventStructure appEvent)
   at ElmFullstack.WebHost.PersistentProcess.PersistentProcessLiveRepresentation.RestoreFromCompositionEventSequence(IEnumerable`1 compositionLogRecords, ElmAppInterfaceConfig overrideElmAppInterfaceConfig)
   at ElmFullstack.WebHost.PersistentProcess.PersistentProcessLiveRepresentation.LoadFromStoreAndRestoreProcess(IProcessStoreReader storeReader, Action`1 logger, ElmAppInterfaceConfig overrideElmAppInterfaceConfig)
   at ElmFullstack.WebHost.StartupAdminInterface.<>c__DisplayClass28_0.<Configure>g__startPublicApp|2()
   at ElmFullstack.WebHost.StartupAdminInterface.Configure(IApplicationBuilder app, IWebHostEnvironment env, IHostApplicationLifetime appLifetime, Func`1 getDateTimeOffset, FileStoreForProcessStore processStoreForFileStore)
```

It crashes because the current implementation depends on a limit similar to the one discussed at: https://github.com/dotnet/runtime/issues/39953

https://github.com/elm-fullstack/elm-fullstack/blob/7ed769b845246ad6adb0ac68c077a6ad250d3f80/implement/elm-fullstack/WebHost/PersistentProcessLiveRepresentation.cs#L249-L251

In our case, it should be `MaxCharacterTokenSize`:
https://github.com/dotnet/runtime/blob/55e2378d86841ec766ee21d5e504d7724c39b53b/src/libraries/System.Text.Json/src/System/Text/Json/JsonConstants.cs#L77

**Comment by mackdunkan** [comment]
Oh thanks for the replies!

**Comment by Viir** [comment]
An update on the scalability front: That bottleneck for database size is now resolved. I ran a test using version 0.4.3 and tested up to one Gigabyte Elm application state size without problems.
Here is the command used for the live test:

```txt
 pine  run-server  --process-store=./proc-store  --delete-previous-process  --deploy=https://github.com/pine-vm/pine/tree/422c9b632d41ad85649165062578142e0f52b6dd/implement/example-apps/test-database-scale
```

As discussed earlier, we switched from JavaScript to a better compilation target and recently removed the last dependencies on JavaScript.
Since the DB size limit resulted from interfacing with a JS engine, such a problem does not exist in the new engine.

The switch to an engine optimized for declarative programming will also increase response times and throughput.
