### ISSUE TITLE
Deploying on Railway

### ISSUE THREAD

**Issue by MattiaVerticchio** [elm-fullstack/elm-fullstack#19]
Hi, first of all, thanks for developing Elm Fullstack! 😁

I’m trying to deploy the test config on [Railway.app](https://railway.app) using the following Dockerfile:

```Dockerfile
FROM ubuntu:22.04

RUN apt update
RUN apt install -y curl unzip

# Download elm-fs
RUN curl --fail --location --output "/elm-fs.zip" "https://github.com/elm-fullstack/elm-fullstack/releases/download/v2022-09-15/elm-fullstack-bin-724de76b6c4d2f87e1e4df487964e2701cc8cef0-linux-x64.zip"

# Unzip and make executable
RUN unzip elm-fs.zip
RUN rm elm-fs.zip elm-fs.pdb
RUN chmod +x elm-fs

# Run test command
ENTRYPOINT [ "/bin/bash", "-l", "-c"]
CMD ["/elm-fs run-server --public-urls=https://elm-fullstack.up.railway.app --deploy=https://github.com/elm-fullstack/elm-fullstack/tree/8ce169c776160db7a035a8d3a7845341af11f871/implement/example-apps/docker-image-default-app"]
```

However, I’m getting this error output:
```
I got no path to a persistent store for the process. This process will not be persisted!
Loading app config to deploy...
This path looks like a URL into a remote git repository. Trying to load from there...
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'source')
at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
at Pine.ZipArchive.ZipArchiveFromEntries(IReadOnlyDictionary`2 entries, CompressionLevel compressionLevel)
at Pine.CacheByFileName.GetOrUpdate(String fileName, Func`1 getNew)
at Pine.LoadFromGitHubOrGitLab.GetRepositoryFilesPartialForCommitDefault(GetRepositoryFilesPartialForCommitRequest request)
at Pine.LoadFromGitHubOrGitLab.LoadFromUrl(String sourceUrl, Func`2 getRepositoryFilesPartialForCommit)
at Pine.ProcessWithLog`2.<>c__DisplayClass12_0`1.<MapResult>b__0(ResultT result)
at Pine.ProcessWithLog`2.Continue[NewResultT](Func`2 continuation)
at Pine.ProcessWithLog`2.<>c__DisplayClass11_0`1.<Continue>b__0()
at Pine.ProcessWithLog`2.<>c__DisplayClass11_0`1.<Continue>b__0()
at Pine.ProcessWithLogExtension.LogToActions[LogEntryT,ResultT](ProcessWithLog`2 firstStep, Action`1 logAction)
at ElmFullstack.WebHost.BuildConfigurationFromArguments.BuildConfigurationZipArchiveFromPath(String sourcePath)
at ElmFullstack.Program.<>c__DisplayClass5_0.<AddRunServerCmd>b__1()
at McMaster.Extensions.CommandLineUtils.CommandLineApplicationExtensions.<>c__DisplayClass9_0.<OnExecute>b__0()
at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
at ElmFullstack.Program.<>c__DisplayClass4_0.<Main>g__executeAndGuideInCaseOfException|4()
at ElmFullstack.Program.Main(String[] args)
```

It’s the first time I use Elm Fullstack, Docker, and Railway, so I’m not sure if I’m doing everything correctly.

Is there something I’m doing wrong?

**Comment by Viir** [comment]
Hello, thank you for sharing your experience!

I was able to repro this runtime exception here with the docker image you posted.
Then I switched the base image to the one from the reference docker build at https://github.com/elm-fullstack/elm-fullstack/blob/81e61aaada9bf95ea16b5cb75c09cd2e5d0b3743/implement/Dockerfile#L11

```
FROM mcr.microsoft.com/dotnet/aspnet:7.0.0-rc.1
```

This base image fixed the crash. Since you tried Ubuntu 22.04, I also tried an image based on Ubuntu 22.04, found at https://hub.docker.com/_/microsoft-dotnet-aspnet/

![image](https://user-images.githubusercontent.com/19209696/193416455-4c0cd055-c5fb-44ce-b8a1-6557b2552ee6.png)

The crash also happens with that base image. I will look into why that is.

If a Debian-based image works for your app, using the mentioned image should be enough to fix it. I don't expect any differences when running on Railway.
